# Generated by Django 2.2.19 on 2022-12-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20221207_2035'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('author', 'name'), name='%(app_label)s_%(class)s_unique_recipe_name'),
        ),
    ]
