# Generated by Django 2.2.19 on 2022-12-06 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20221206_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quantityofingredients',
            options={'ordering': ('ingredient',), 'verbose_name': 'Ингридиент', 'verbose_name_plural': 'Количество ингридиентов'},
        ),
    ]
