# Generated by Django 2.2.19 on 2022-12-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20221208_1248'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='%(app_label)s_%(class)s_unique_ingredient',
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='%(app_label)s_%(class)s_unique_object'),
        ),
    ]
